spring:  
  jpa:  
    hibernate:  
      ddl-auto: create  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://your_dbserver"  
    username: tkcsowner  
    password: tkcsowner
  rabbitmq:
    host: "rabbitserver"
    password: iamowner
    port:   5672
    username: iamowner

rmq:
  test:
    exchange: amq.direct
    queue: kk.test.queue
    routingkey: kk.test.routingkey

   